// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmN246BrzOpy3zRYUj4kmpb-bMAw1eXJA',
    appId: '1:504949843137:web:3b3c2df0094b67e9962040',
    messagingSenderId: '504949843137',
    projectId: 'pet-app-7c07c',
    authDomain: 'pet-app-7c07c.firebaseapp.com',
    storageBucket: 'pet-app-7c07c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQBJVo3A133BBA9QhRHj0QHA2FtuNBVig',
    appId: '1:504949843137:android:dde10dd5daa47025962040',
    messagingSenderId: '504949843137',
    projectId: 'pet-app-7c07c',
    storageBucket: 'pet-app-7c07c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWoL94sVBJQUjIRWXhShIgtR2fSordzrQ',
    appId: '1:504949843137:ios:08b61463393af78a962040',
    messagingSenderId: '504949843137',
    projectId: 'pet-app-7c07c',
    storageBucket: 'pet-app-7c07c.appspot.com',
    iosClientId: '504949843137-mnf8h5ct6gmromv6ep0stamhl1dhvpq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWoL94sVBJQUjIRWXhShIgtR2fSordzrQ',
    appId: '1:504949843137:ios:08b61463393af78a962040',
    messagingSenderId: '504949843137',
    projectId: 'pet-app-7c07c',
    storageBucket: 'pet-app-7c07c.appspot.com',
    iosClientId: '504949843137-mnf8h5ct6gmromv6ep0stamhl1dhvpq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );
}
